services:
  postgresdb:
    image: postgres:14
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_PG_USER}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
    ports:
      - "5432"

  backend:
    build:
      context: ./api 
      dockerfile: Dockerfile 
    container_name: backend
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile 
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: